export const landformModules = [
  {
    id: 'karst',
    icon: '🕳',
    label: '喀斯特地貌',
    subtitle: '岩溶地貌 · 桂林山水',
    description: '喀斯特地貌是可溶性岩石（以石灰岩为主）受地表水、地下水的溶蚀作用所形成的各种地貌。我国广西、贵州、云南等地最为典型。',
    keyPoints: [
      '溶蚀作用：含 CO₂ 的水对石灰岩的化学溶解过程',
      '地表形态：溶沟、洼地、峰丛、峰林、孤峰、残丘',
      '地下形态：溶洞、石钟乳、石笋、石柱、地下河',
      '分布：桂、黔、滇碳酸盐岩出露地区',
    ],
    advancedPoints: [
      '岩溶动力系统：CO₂-H₂O-CaCO₃ 三相平衡与溶蚀速率',
      '岩溶地貌演化序列：溶沟→洼地→峰丛→峰林→孤峰→残丘（Davis 循环）',
      '表层岩溶带（Epikarst）对地下水调蓄的关键作用',
      '石漠化：植被破坏→水土流失→基岩裸露的退化过程',
      '岩溶碳汇效应：全球碳酸盐岩风化对 CO₂ 循环的贡献',
    ],
    references: [
      'Ford, D.C. & Williams, P. (2007). Karst Hydrogeology and Geomorphology. Wiley.',
      'Yuan, D. (1997). Sensitivity of karst process to environmental change. Episodes, 20(2), 88-92.',
    ],
    params: [
      { label: 'CaCO₃ 溶解度', value: '15-50 mg/L' },
      { label: '溶蚀速率', value: '0.01-0.5 mm/yr' },
      { label: '峰林坡角', value: '45°-90°' },
    ],
  },
  {
    id: 'fluvial',
    icon: '🏞',
    label: '河流地貌',
    subtitle: '流水侵蚀与堆积',
    description: '河流通过侵蚀、搬运和堆积作用塑造地表形态。上游形成 V 形谷，中游发育河曲，下游形成冲积平原和三角洲。',
    keyPoints: [
      '侵蚀类型：下蚀（V形谷）、侧蚀（河曲）、溯源侵蚀',
      '堆积地貌：冲积扇、河漫滩、三角洲、冲积平原',
      '河流发育阶段：青年期（下蚀）→ 壮年期（侧蚀）→ 老年期（堆积）',
      '河流地貌与人类活动：农业、聚落、交通选址',
    ],
    advancedPoints: [
      '水力几何关系（Leopold & Maddock）：宽深比与流量幂律',
      '侵蚀循环理论（Davis）：幼年→壮年→老年地形序列',
      '河流纵剖面均衡理论（Strahler 面积-高程分析）',
      '河型分类：顺直、曲流、辫状、网状——水沙条件控制',
      '输沙率公式：Bagnold / Einstein 床沙质输移模型',
    ],
    references: [
      'Leopold, L.B., Wolman, M.G. & Miller, J.P. (1992). Fluvial Processes in Geomorphology. Dover.',
      'Knighton, D. (1998). Fluvial Forms and Processes. Arnold.',
      'Strahler, A.N. (1957). Quantitative analysis of watershed geomorphology. Eos, 38(6), 913-920.',
    ],
    params: [
      { label: '曼宁系数 n', value: '0.025-0.05' },
      { label: '推移质输沙率', value: '10⁻³-10⁻¹ kg/s·m' },
      { label: '河流坡度', value: '0.001-0.01' },
    ],
  },
  {
    id: 'aeolian',
    icon: '🏜',
    label: '风沙地貌',
    subtitle: '风力侵蚀与堆积',
    description: '风沙地貌是风力对地表物质的侵蚀、搬运和堆积所形成的各种地貌形态，主要分布在干旱和半干旱地区。',
    keyPoints: [
      '风蚀地貌：雅丹（风蚀垄槽）、风蚀柱、风蚀蘑菇、风蚀洼地',
      '风积地貌：沙丘（新月形沙丘、纵向沙垄、金字塔沙丘）',
      '沙丘移动：迎风坡缓（5°-15°）、背风坡陡（30°-34°）',
      '黄土：风力搬运堆积形成，主要分布在黄土高原',
    ],
    advancedPoints: [
      '沙粒起动阈值风速：Bagnold 公式 u*_t = A √(gd(ρs-ρ)/ρ)',
      '沙丘形态动力学：迎风坡流速加速→侵蚀，背风坡分离→堆积',
      '雅丹发育与风蚀速率：实测年均风蚀深度 0.1-5 cm',
      '腾格里/巴丹吉林沙漠形成演化与第四纪气候',
      '粉尘循环（Dust Cycle）：亚洲粉尘对全球气候的反馈效应',
    ],
    references: [
      'Bagnold, R.A. (1941). The Physics of Blown Sand and Desert Dunes. Methuen.',
      'Pye, K. & Tsoar, H. (2009). Aeolian Sand and Sand Dunes. Springer.',
      '张克存等 (2020). 中国沙漠风沙地貌学. 科学出版社.',
    ],
    params: [
      { label: '起动风速', value: '5-6 m/s (2m高)' },
      { label: '输沙率 Q', value: 'Q ∝ u*³' },
      { label: '沙丘移动速率', value: '5-20 m/yr' },
    ],
  },
  {
    id: 'coastal',
    icon: '🌊',
    label: '海岸地貌',
    subtitle: '海浪与潮流塑造',
    description: '海岸地貌是在波浪、潮汐、海流等海洋动力作用下形成的各种地貌形态，包括侵蚀型和堆积型两大类。',
    keyPoints: [
      '海蚀地貌：海蚀崖、海蚀平台、海蚀洞、海蚀拱桥、海蚀柱',
      '海积地貌：海滩（砾滩/砂滩/泥滩）、沙嘴、沙坝、潟湖',
      '三角洲：河流与海洋共同作用形成的堆积体',
      '海岸类型：基岩海岸、砂质海岸、淤泥质海岸、生物海岸',
    ],
    advancedPoints: [
      '波浪折射与沿岸输沙：CERC 公式 Q = K H_b^(5/2) sin(2α_b)',
      '海平面变化对海岸的影响：IPCC RCP 8.5 情景下2050年海面上升预测',
      '三角洲形态分类：鸟足状（密西西比）、扇形（尼罗河）、尖头（长江）',
      '海岸侵蚀与防护：硬工程（丁坝、防波堤）vs 软工程（海滩 nourish）',
      '珊瑚礁/红树林海岸生态地貌反馈系统',
    ],
    references: [
      'Bird, E. (2008). Coastal Geomorphology: An Introduction. Wiley.',
      'Komar, P.D. (1998). Beach Processes and Sedimentation. Prentice Hall.',
      '王颖 (2013). 中国海洋地理. 科学出版社.',
    ],
    params: [
      { label: '波浪能通量 P', value: 'P = ρgH²Cg/8' },
      { label: '沿岸输沙率', value: '10⁵-10⁶ m³/yr' },
      { label: '潮差类型', value: '0.5-8 m' },
    ],
  },
]
